<?php

namespace sumaysigue\modelo;

require "vendor/autoload.php";

use sumaysigue\modelo\saludo;
/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-22 at 12:45:13.
 */
class saludoTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var saludo
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new saludo;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers sumaysigue\modelo\saludo::setSaludo
     * @todo   Implement testSetSaludo().
     */

    /**
     * @covers sumaysigue\modelo\saludo::formatSaludo
     * @todo   Implement testFormatSaludo().
     */
    
    /*
     * @dataProvider proveedorTestFormatSaludo
     */
    public function testFormatSaludo($saludo, $saludoEspeado) {
        $this->object->setSaludo($saludo);
        $saludoObtenido=$this->object->formatSaludo();
        $this->assertEquals($saludoEspeado, $saludoObtenido);
    }
    
    public function proveedorTestFormatSaludo(){
        return [
          "Saludo 1" => ["hola","El mensaje es: Hola"],
          "Saludo 2" => ["Adios","El mensaje es: Adios"]
        ];
    }

}
